apiVersion: v1
baseDomain: example.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: <cluster_name>
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    failureDomains:
      - name: Testing
        region: one
        server: vcenter.ncgr.sa
        topology:
          computeCluster: "<datacenter/host/cluster"
          datacenter: datacenter
          datastore: "/datacenter/datastore/datastore" 
          networks:
          - VM_Network_name
          resourcePool: "/datacenter/host/cluster/Resources/resourcePool"
          folder: "/datacenter_name/vm/folder_name/subfolder_name"
        zone: default_zone_name
    vcenters:
      - datacenters:
        - DC1
        password: Password@!
        port: 443
        server: vcenter.ncgr.sa
        user: administrator@vsphere.local
    diskType: thin
    apiVIP: 192.168.0.10
    ingressVIP: 192.168.0.11
pullSecret: ''
sshKey: ''
additionalTrustedBundle: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
